---
abstract: "DROLSKY's plugin bundle"
author:
  - 'Dave Rolsky <autarch@urth.org>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.015, CPAN::Meta::Converter version 2.120921'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-PluginBundle-DROLSKY
requires:
  Dist::Zilla: 0
  Dist::Zilla::Plugin::Authority: 0
  Dist::Zilla::Plugin::AutoPrereqs: 0
  Dist::Zilla::Plugin::CheckPrereqsIndexed: 0
  Dist::Zilla::Plugin::ContributorsFromGit: 0
  Dist::Zilla::Plugin::CopyReadmeFromBuild: 0
  Dist::Zilla::Plugin::EOLTests: 0
  Dist::Zilla::Plugin::Git::Check: 0
  Dist::Zilla::Plugin::Git::Commit: 0
  Dist::Zilla::Plugin::Git::Push: 0
  Dist::Zilla::Plugin::Git::Tag: 0
  Dist::Zilla::Plugin::InstallGuide: 0
  Dist::Zilla::Plugin::Meta::Contributors: 0
  Dist::Zilla::Plugin::MetaJSON: 0
  Dist::Zilla::Plugin::MetaResources: 0
  Dist::Zilla::Plugin::NextRelease: 0
  Dist::Zilla::Plugin::PkgVersion: 0
  Dist::Zilla::Plugin::PodCoverageTests: 0
  Dist::Zilla::Plugin::PodSyntaxTests: 0
  Dist::Zilla::Plugin::PruneFiles: 0
  Dist::Zilla::Plugin::ReadmeFromPod: 0
  Dist::Zilla::Plugin::SurgicalPodWeaver: 0
  Dist::Zilla::Plugin::Test::CPAN::Changes: 0
  Dist::Zilla::Plugin::Test::Compile: 0
  Dist::Zilla::Plugin::Test::NoTabs: 0
  Dist::Zilla::Plugin::Test::Pod::LinkCheck: 0
  Dist::Zilla::Plugin::Test::Pod::No404s: 0
  Dist::Zilla::Plugin::Test::PodSpelling: 0
  Dist::Zilla::Plugin::Test::Synopsis: 0
  Dist::Zilla::Role::PluginBundle::Easy: 0
  Moose: 0
  Pod::Weaver::Section::Contributors: 0
  perl: v5.10.0
  strict: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Dist-Zilla-PluginBundle-DROLSKY
  homepage: http://metacpan.org/release/Dist-Zilla-PluginBundle-DROLSKY
  repository: git://git.urth.org/Dist-Zilla-PluginBundle-DROLSKY.git
version: 0.09
x_authority: cpan:DROLSKY
