---
abstract: "DROLSKY's plugin bundle"
author:
  - 'Dave Rolsky <autarch@urth.org>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300039, CPAN::Meta::Converter version 2.131560'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-PluginBundle-DROLSKY
requires:
  Dist::Zilla: 0
  Dist::Zilla::Role::PluginBundle::Easy: 0
  Moose: 0
  perl: v5.10.0
  strict: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Dist-Zilla-PluginBundle-DROLSKY
  homepage: http://metacpan.org/release/Dist-Zilla-PluginBundle-DROLSKY
  repository: git://git.urth.org/Dist-Zilla-PluginBundle-DROLSKY.git
version: 0.05
x_authority: cpan:DROLSKY
